/* Interface text built in code, looked up with t('key', {vars}). Use {name} for runtime values. */
const STRINGS = {
  pageTitle: "PaperLens – Research Paper Classification",
  navAnalyze: "Classify a paper",
  navJournals: "Journal search",
  navCompare: "Compare",
  navAbout: "About",
  compareTitle: "Compare journals",
  opensNewTab: "opens in a new tab",
  copied: "Copied to clipboard",
  copyFailed: "The text could not be copied. Please select and copy it manually.",
  errTimeout: "The server did not respond in time. Please try again shortly.",
  errNetwork: "PaperLens could not be reached. Please check your internet connection and try again.",
  errServer: "An unexpected server error occurred. Please try again.",
  errEmptyQuery: "Please enter a DOI, an arXiv identifier or link, or the title of the paper.",
  errTooManyFiles: "Up to {n} documents can be analyzed at once. Additional documents were not added.",
  errFileType: "Only PDF and Word (.docx) documents are supported. Not added: {names}",
  errFileSize: "Documents must not exceed 50 MB. Not added: {names}",
  stepSearching: "Locating the paper…",
  stepDatabases: "Verifying metadata with CrossRef, OpenAlex and Semantic Scholar…",
  stepRanking: "Retrieving journal and conference rankings…",
  stepUploading: "Uploading the document…",
  stepUploadingMany: "Uploading {n} documents…",
  stepReading: "Analyzing the document…",
  selectedFile: "Selected document",
  selectedFiles: "Selected documents ({n})",
  removeFile: "Remove {name}",
  catJournal: "Journal",
  catConference: "Conference",
  catPreprint: "Preprint",
  catUnknown: "Undetermined",
  unranked: "Unranked",
  unknownTitle: "Untitled paper",
  alsoOnArxiv: "Also on arXiv",
  verdictJournalQ: "Journal article · {q} journal",
  verdictJournalUnranked: "Journal article · journal not ranked by Scimago",
  verdictJournalScopusOnly: "Journal article · indexed in Scopus, no quartile yet",
  verdictJournalDiscontinued: "Journal article · journal discontinued by Scopus",
  explainJournalScopusOnly: "The journal is on the Scopus source list but has not yet received a Scimago quartile, which usually means it was indexed recently. Its standing should be judged with care until a quartile is assigned.",
  explainJournalDiscontinued: "Scopus stopped indexing this journal{year}. Any quartile shown reflects an earlier edition of the ranking; many institutions no longer accept papers in discontinued journals.",
  verdictConfRank: "Conference paper · CORE rank {rank}",
  verdictConfNational: "Conference paper · national or regional conference",
  verdictConfUnranked: "Conference paper · conference not ranked by CORE",
  verdictPreprint: "Preprint · not yet peer reviewed",
  verdictUnknown: "The publication type could not be determined",
  explainQ1: "The journal ranks in the top 25% of its subject category by citation impact, the highest quartile.",
  explainQ2: "The journal ranks between the 25th and 50th percentile of its subject category by citation impact.",
  explainQ3: "The journal ranks between the 50th and 75th percentile of its subject category by citation impact.",
  explainQ4: "The journal ranks in the lowest 25% of its subject category by citation impact. It remains indexed in Scopus.",
  explainJournalUnranked: "The journal does not appear in the Scimago (Scopus) ranking. This is common for new or specialised journals, but the journal should be verified before it is relied upon.",
  explainRankAStar: "A* denotes a flagship conference, approximately the top 7% of computing conferences.",
  explainRankA: "A denotes an excellent conference, approximately the top 20% of computing conferences.",
  explainRankB: "B denotes a good conference that is well regarded in its area.",
  explainRankC: "C denotes a conference that meets minimum academic standards.",
  explainNational: "The conference is a national or regional event intended primarily for researchers from one country or region.",
  explainConfUnranked: "CORE ranks computing conferences only; conferences in other fields are generally unranked.",
  explainPreprint: "The paper has been made public without peer review. Suitable ranked journals for submission are listed below.",
  explainUnknown: "There was insufficient evidence to classify the paper. Searching by its DOI is recommended.",
  confidence_high: "High confidence",
  confidence_medium: "Medium confidence",
  confidence_low: "Low confidence",
  confidenceSr: "Confidence {pct} percent, {level}.",
  confType_IEEE: "IEEE conference",
  confType_International: "International conference",
  confType_National: "National conference",
  factVenue: "Venue",
  factConference: "Conference",
  factRepository: "Repository",
  factRank: "Ranking",
  factConfType: "Conference type",
  factPublisher: "Publisher",
  factYear: "Year",
  factCitations: "Citations",
  factPublishedVersion: "Published version",
  factFreeCopy: "Open-access copy",
  readFree: "View open-access copy",
  factSubjects: "Subjects",
  factPages: "Pages",
  trustTitle: "Verification",
  trustInSjr: "Journal holds a Scimago (SJR) quartile",
  trustNotInSjr: "Journal is not in the Scimago (Scopus) ranking",
  trustInCore: "Conference is listed in the CORE ranking",
  trustNotInCore: "Conference is not in the CORE ranking",
  trustInDoaj: "Journal is listed in the Directory of Open Access Journals (DOAJ)",
  trustNotInDoaj: "Journal is not listed in DOAJ either",
  trustNotRetracted: "No retraction notice found",
  trustOpenAccess: "An open-access copy is available",
  trustInScopus: "Journal is on the Scopus source list (active)",
  trustNotInScopus: "Journal is not on the Scopus source list",
  trustScopusDiscontinued: "Scopus discontinued this journal{year}",
  trustDoajNoFees: "DOAJ records no article processing charge",
  trustDoajFees: "DOAJ records an article processing charge of {amount}",
  trustDoajReview: "Review process reported to DOAJ: {process}",
  trustNoWatchlist: "Not on the hijacked-journal or predatory lists",
  hijackedTitle: "A fake copy of this journal exists",
  hijackedText: "Retraction Watch lists a hijacked website that imitates {name}. Submit and cite only through the publisher’s own site: ",
  hijackedNoUrl: "Retraction Watch lists a hijacked website that imitates {name}. Verify the publisher’s website before submitting or paying any fee.",
  predatoryTitle: "Journal name appears on a predatory-journal list",
  predatoryText: "“{name}” is listed by Stop Predatory Journals, a community-maintained list. A legitimate journal may share the name, so check the website, editorial board and fees carefully before relying on it.",
  predatoryPublisherTitle: "Publisher appears on a predatory-publisher list",
  predatoryPublisherText: "The publisher “{name}” is listed by Stop Predatory Journals, a community-maintained list. Verify the journal’s peer review and indexing before submitting or citing.",
  discontinuedTitle: "Scopus has discontinued this journal",
  discontinuedText: "Scopus stopped indexing this journal{year} ({reason}). Papers published after that date are not indexed in Scopus, and the quartile shown may be from an earlier ranking edition.",
  reasonDiscontinuation: "publication concerns",
  reasonPolicy: "a change of journal policy",
  factImpact: "Citation impact (OpenAlex)",
  impactHint: "No official ranking exists for this venue. These figures are computed by OpenAlex from its own citation data and are an estimate, not a rank.",
  impactHIndex: "h-index {h}",
  impactCitedness: "{n} citations per paper (2 years)",
  impactWorks: "{n} papers indexed",
  factFees: "Publication fee (DOAJ)",
  feesNone: "None",
  dataEditions: "Rankings and lists in use",
  retractedTitle: "This paper has been retracted",
  retractedText: "The publisher has withdrawn this paper. It should not be cited as valid research.",
  notIndexedTitle: "Verify this journal before relying on it",
  notIndexedText: "The journal is indexed in neither Scopus (Scimago) nor DOAJ. This does not establish that it is predatory, but its editorial board, review process and fees should be examined before submission or citation.",
  suggestTitle: "Recommended journals in {field}",
  suggestHint: "Ordered by SJR score. The scope of each journal should be reviewed before submission.",
  colJournal: "Journal",
  colQuartile: "Quartile",
  colActions: "Actions",
  colPaper: "Paper",
  colType: "Type",
  colConfidence: "Confidence",
  colMeasure: "Measure",
  whyTitle: "Evidence",
  abstractTitle: "Abstract",
  copySummary: "Copy summary",
  copyBibtex: "Copy BibTeX",
  viewLoading: "Loading…",
  viewFailed: "This part of PaperLens could not be loaded. Please reload the page.",
  copyLink: "Copy link",
  printReport: "Print or save as PDF",
  checkAnother: "Classify another paper",
  summaryVerdict: "Result",
  summaryConfidence: "Confidence",
  bulkTitle: "Results for {n} papers",
  bulkUnclear: "Undetermined or failed",
  bulkErrors: "Documents that could not be analyzed",
  exportCsv: "Download CSV",
  newBatch: "New batch",
  historyCleared: "History cleared",
  addCompare: "Compare",
  inCompare: "Added",
  compareFull: "Up to {n} journals can be compared. Please remove one first.",
  addedToCompare: "Added to Compare",
  remove: "Remove",
  highestSjr: "Highest SJR",
  country: "Country",
  openAccess: "Open access",
  yes: "Yes",
  no: "No",
  moreInfo: "More info",
  loading: "Loading…",
  journalsFound: "{n} journals found",
  noJournals: "No journals match the search. Try fewer words or remove a filter.",
  pageOf: "Page {page} of {pages}",
} as const;

export type StringKey = keyof typeof STRINGS;

export function t(key: StringKey, vars: Record<string, string | number> = {}): string {
  let text: string = STRINGS[key] ?? key;
  for (const [k, v] of Object.entries(vars)) text = text.split('{' + k + '}').join(String(v));
  return text;
}
